INSERT INTO mytable(province_id,province_th,province_en,country_id) VALUES
 (10,'กรุงเทพมหานคร','Bangkok',1)
,(11,'สมุทรปราการ','Samut Prakarn',1)
,(12,'นนทบุรี','Nonthaburi',1)
,(13,'ปทุมธานี','Pathum Thani',1)
,(14,'พระนครศรีอยุธยา','Phra Nakhon Si Ayutthaya',1)
,(15,'อ่างทอง','Ang Thong',1)
,(16,'ลพบุรี','Lop Buri',1)
,(17,'สิงห์บุรี','Sing Buri',1)
,(18,'ชัยนาท','Chai Nat',1)
,(19,'สระบุรี','Saraburi',1)
,(20,'ชลบุรี','Chon Buri',1)
,(21,'ระยอง','Rayong',1)
,(22,'จันทบุรี','Chanthaburi',1)
,(23,'ตราด','Trat',1)
,(24,'ฉะเชิงเทรา','Chachoengsao',1)
,(25,'ปราจีนบุรี','Prachin Buri',1)
,(26,'นครนายก','Nakhon Nayok',1)
,(27,'สระแก้ว','Sa kaeo',1)
,(30,'นครราชสีมา','Nakhon Ratchasima',1)
,(31,'บุรีรัมย์','Buri Ram',1)
,(32,'สุรินทร์','Surin',1)
,(33,'ศรีสะเกษ','Si Sa Ket',1)
,(34,'อุบลราชธานี','Ubon Ratchathani',1)
,(35,'ยโสธร','Yasothon',1)
,(36,'ชัยภูมิ','Chaiyaphum',1)
,(37,'อำนาจเจริญ','Amnat Charoen',1)
,(38,'บึงกาฬ','Bueng Kan',1)
,(39,'หนองบัวลำภู','Nong Bua Lam Phu',1)
,(40,'ขอนแก่น','Khon Kaen',1)
,(41,'อุดรธานี','Udon Thani',1)
,(42,'เลย','Loei',1)
,(43,'หนองคาย','Nong Khai',1)
,(44,'มหาสารคาม','Maha Sarakham',1)
,(45,'ร้อยเอ็ด','Roi Et',1)
,(46,'กาฬสินธุ์','Kalasin',1)
,(47,'สกลนคร','Sakon Nakhon',1)
,(48,'นครพนม','Nakhon Phanom',1)
,(49,'มุกดาหาร','Mukdahan',1)
,(50,'เชียงใหม่','Chiang Mai',1)
,(51,'ลำพูน','Lamphun',1)
,(52,'ลำปาง','Lampang',1)
,(53,'อุตรดิตถ์','Uttaradit',1)
,(54,'แพร่','Phrae',1)
,(55,'น่าน','Nan',1)
,(56,'พะเยา','Phayao',1)
,(57,'เชียงราย','Chiang Rai',1)
,(58,'แม่ฮ่องสอน','Mae Hong Son',1)
,(60,'นครสวรรค์','Nakhon Sawan',1)
,(61,'อุทัยธานี','Uthai Thani',1)
,(62,'กำแพงเพชร','Kamphaeng Phet',1)
,(63,'ตาก','Tak',1)
,(64,'สุโขทัย','Sukhothai',1)
,(65,'พิษณุโลก','Phitsanulok',1)
,(66,'พิจิตร','Phichit',1)
,(67,'เพชรบูรณ์','Phetchabun',1)
,(70,'ราชบุรี','Ratchaburi',1)
,(71,'กาญจนบุรี','Kanchanaburi',1)
,(72,'สุพรรณบุรี','Suphan Buri',1)
,(73,'นครปฐม','Nakhon Pathom',1)
,(74,'สมุทรสาคร','Samut Sakhon',1)
,(75,'สมุทรสงคราม','Samut Songkhram',1)
,(76,'เพชรบุรี','Phetchaburi',1)
,(77,'ประจวบคีรีขันธ์','Prachuap Khiri Khan',1)
,(80,'นครศรีธรรมราช','Nakhon Si Thammarat',1)
,(81,'กระบี่','Krabi',1)
,(82,'พังงา','Phang-nga',1)
,(83,'ภูเก็ต','Phuket',1)
,(84,'สุราษฎร์ธานี','Surat Thani',1)
,(85,'ระนอง','Ranong',1)
,(86,'ชุมพร','Chumphon',1)
,(90,'สงขลา','Songkhla',1)
,(91,'สตูล','Satun',1)
,(92,'ตรัง','Trang',1)
,(93,'พัทลุง','Phatthalung',1)
,(94,'ปัตตานี','Pattani',1)
,(95,'ยะลา','Yala',1)
,(96,'นราธิวาส','Narathiwat',1);
